Update keys.c
kazu-yamamoto/pgpdump pull request #34
Opened 2022-03-01 12:41 UTC by galaxiesFarApart

2022-03-01: insert "memset" where ELLIP_CURVES are evaluated to re-initialize the "oid_input_HEX" array to all zero; left as it was, multiple different ECC curve evaluations may leave remnants of earlier read input values which can cause "memcpy" to fail (for "invalid/undefined/unmatched values") -> segfault; most notable when evaluating "keys" with a plethora of packets with different ECC algorithms

2022-03-01 12:44 UTC, galaxiesFarApart commented
Ah  - phooey. I didn't really mean to close PR#34 (having problems determining status of created PRs)

2022-03-09 10:41 UTC, galaxiesFarApart commented
Attached are dump outputs and test key file that results in segfault (which really occurs in "printf" statement). Same files have also been sent through e-mail.

[ggp234-ecc-Brainpool-P256-test-2022-03-01.pubkey.zip](https://github.com/kazu-yamamoto/pgpdump/files/8213760/ggp234-ecc-Brainpool-P256-test-2022-03-01.pubkey.zip)
[Multiple_ECC_algos_with_many_packets-segfault-2022-03-01.log.zip](https://github.com/kazu-yamamoto/pgpdump/files/8213761/Multiple_ECC_algos_with_many_packets-segfault-2022-03-01.log.zip)
[Multiple_ECC_algos_with_many_packets-with_memset-2022-03-01.log.zip](https://github.com/kazu-yamamoto/pgpdump/files/8213762/Multiple_ECC_algos_with_many_packets-with_memset-2022-03-01.log.zip)

2022-04-13 04:31 UTC, kazu-yamamoto requested changes
Sorry for the delay. And nice catch!

2022-04-13 04:31 UTC, kazu-yamamoto commented on keys.c
> +		memset(oid_input_HEX,0,10);
I would like to avoid hard-coding a magic number. Could you use `oid_input_HEX_size` instead of `10`?

2022-04-14 05:06 UTC, kazu-yamamoto approved these changes
Now LTGM

2022-04-14 05:12 UTC, kazu-yamamoto commented
Cherry-picked and merged. Thank you for your contribution!

2022-04-14 05:12 UTC, closed without merging

2022-10-11 09:14 UTC, galaxiesFarApart commented
Yes - using "size" can be done. I had thought of not using 10 realizing that that value could change in the future, but I already had that value established from RFCs. I will work on the change.

Sent from my iPad - J.Dutton

> On Apr 12, 2022, at 11:31 PM, Kazu Yamamoto ***@***.***> wrote:
> 
> ﻿
> @kazu-yamamoto requested changes on this pull request.
> 
> Sorry for the delay. And nice catch!
> 
> In keys.c:
> 
> > @@ -125,6 +125,7 @@ new_Public_Key_Packet(int len)
>  		break;
>  	case 18:/*ECDH*/
>  		oidLEN = Getc();
> +		memset(oid_input_HEX,0,10);
> I would like to avoid hard-coding a magic number. Could you use oid_input_HEX_size instead of 10?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.